version: '2.1'

services:
    mavros-avoidance:
        extends:
            file: ../../../components/components.yml
            service: mavros-avoidance
        command: "fcu_url:=\"tcp://172.17.0.1:5760\""
    realsense-node:
        extends:
            file: ../../../components/components.yml
            service: realsense-node
        privileged: true
        environment:
            - ROS_MASTER_URI=http://mavros-avoidance:11311
    avoidance-node:
        extends:
            file: ../../../components/components.yml
            service: avoidance-node
        depends_on:
            - mavros-avoidance
            - realsense-node
        environment:
            - ROS_MASTER_URI=http://mavros-avoidance:11311
        command: global_avoidance.launch use_sim_time:=false
    alpinevpn:
        extends:
            file: ../../../components/components.yml
            service: alpinevpn
