version: '2.1'

services:
    mavros-avoidance:
        extends:
            file: ../../components/components.yml
            service: mavros-avoidance
        command: fcu_url:="udp://:14540@sitl-avoidance-server:14557" use_sim_time:="true"
    sitl-avoidance-server:
        extends:
            file: ../../components/components.yml
            service: sitl-avoidance-server
        depends_on:
            - mavros-avoidance
    sitl-avoidance-gui:
        extends:
            file: ../../components/components.yml
            service: sitl-avoidance-gui
        depends_on:
            - sitl-avoidance-server
        command: /root/resource/global_planner.rviz
    global-planner-node:
        extends:
            file: ../../components/components.yml
            service: global-planner-node
        depends_on:
            - sitl-avoidance-server
        command: global_avoidance.launch use_sim_time:="true"
