version: '2.1'
services:
    mavros:
        build: ./mavros/
        ports:
            - "11311:11311"
    mavros-avoidance:
        build:
            context: ../..
            dockerfile: docker/components/mavros-avoidance/Dockerfile
        command: fcu_url:="udp://:14540@sitl-avoidance-server:14557"
        ports:
            - "11311:11311"
    sitl-avoidance-server:
        build:
            context: ../..
            dockerfile: docker/components/sitl-server/Dockerfile
        ports:
            - "14556:14556/udp"
            - "14557:14557/udp"
            - "11345:11345"
        privileged: true
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
    sitl-avoidance-gui:
        build:
            context: ../..
            dockerfile: docker/components/sitl-gui/Dockerfile
        privileged: true
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:ro
    local-planner-node:
        build:
            context: ../..
            dockerfile: docker/components/local-planner-node/Dockerfile
    global-planner-node:
        build:
            context: ../..
            dockerfile: docker/components/global-planner-node/Dockerfile
    realsense-node:
        build: ./realsense-node/
    alpinevpn:
        build: ./alpinevpn/
        ports:
            - "1194:1194/udp"
        privileged: true
